# Generated by Django 4.2.5 on 2023-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_month_year_week_month_year_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
