# Generated by Django 4.2.5 on 2023-09-22 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_month_sales_amount_week_sales_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(default=django.utils.timezone.now)),
                ('stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_counted', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.stocktake')),
            ],
        ),
        migrations.AddField(
            model_name='stocktake',
            name='products',
            field=models.ManyToManyField(through='product.StockTakeItem', to='product.product'),
        ),
    ]
