# Generated by Django 4.2.5 on 2023-09-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_stocktake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='stock_balanced',
            field=models.BooleanField(default=False),
        ),
    ]
