# Generated by Django 4.2.5 on 2023-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_stocktake_stock_balanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('product_code__isnull', False)), fields=('product_code',), name='unique_product_code'),
        ),
    ]
