# Generated by Django 4.2.5 on 2023-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_product_code_product_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
