# Generated by Django 4.2.5 on 2023-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_buyer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
