# Generated by Django 4.2.5 on 2023-10-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_cart_total_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='add_vat',
            field=models.BooleanField(default=False),
        ),
    ]
