# Generated by Django 4.2.5 on 2023-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_sale_add_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='add_vat',
        ),
        migrations.AddField(
            model_name='cart',
            name='add_vat',
            field=models.BooleanField(default=False),
        ),
    ]
