# Generated by Django 4.2.5 on 2023-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_cart_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
