# Generated by Django 4.2.5 on 2023-10-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_total_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_value',
            new_name='products_value',
        ),
    ]
