# Generated by Django 4.2.5 on 2023-10-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_rename_total_value_product_products_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products_value',
        ),
    ]
