# Generated by Django 4.2.5 on 2023-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_stocktake_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
