# Generated by Django 4.2.5 on 2023-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products_supplied',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='product.category'),
        ),
    ]
