# Generated by Django 4.2.5 on 2023-11-25 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0036_cart_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(through='product.ReceivedProduct', to='product.product')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='receivedproduct',
            name='receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.receiving'),
        ),
        migrations.AlterUniqueTogether(
            name='receivedproduct',
            unique_together={('receiving', 'product')},
        ),
    ]
