# Generated by Django 4.2.5 on 2023-11-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_supply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedproduct',
            old_name='quantity_received',
            new_name='product_quantity',
        ),
    ]
