# Generated by Django 4.2.5 on 2023-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_rename_quantity_received_receivedproduct_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedproduct',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
