# Generated by Django 4.2.5 on 2023-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_promotion_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
