# Generated by Django 4.2.5 on 2023-12-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products_supplied',
        ),
    ]
