# Generated by Django 4.2.5 on 2023-12-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_supplier_category_supplier_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
    ]
