# Generated by Django 4.2.5 on 2023-12-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_supplier_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='product.category'),
        ),
    ]
