# Generated by Django 4.2.6 on 2023-12-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_supplier_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='products',
        ),
        migrations.AddField(
            model_name='receiving',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
