# Generated by Django 4.2.6 on 2024-03-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0054_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Sales')),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Expenses')),
                ('cash_at_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cash at Hand')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Cashup',
                'verbose_name_plural': 'Cashups',
            },
        ),
    ]
