# Generated by Django 4.2.6 on 2024-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_cashup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashed_up',
            field=models.BooleanField(default=False),
        ),
    ]
