# Generated by Django 4.2.6 on 2024-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_sale_cashed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashup',
            name='stock_value_before_cashup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
